[package]
name = "compiler-exp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.1.15"
antlr-rust = "0.2"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm13-0"] }
codespan-reporting = "0.11.1"
